<table>
    <head>
        <tr>
            <th>No</th>
            <th>Nama</th>
        </tr>
    </head>
    <tbody>
        <tr>
            <td>1</td>
            <td>asdsad</td>
        </tr>
    </tbody>
</table>
